// See https://aka.ms/new-console-template for more information
using BenchmarkDotNet.Running;
using System.Collections;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;
using Trarizon.Library;
using Trarizon.Library.CodeAnalysis;
using Trarizon.Library.Collections.AllocOpt;
using Trarizon.Library.Collections.Helpers;
using Trarizon.Library.RunTest.Examples;
using Trarizon.Library.Wrappers;
using Trarizon.Test.Run;

AllocOptQueue<object> queue = new(4);
queue.Enqueue(1);
queue.Enqueue(2);
queue.Enqueue(3);
queue.Dequeue();
queue.Enqueue(4);
queue.Print();
queue.GetUnderlyingArray().Print();
queue.Enqueue(5);
queue.Print();
queue.GetUnderlyingArray().Print();
queue.Dequeue();
queue.Dequeue();
queue.Print();
queue.GetUnderlyingArray().Print();
queue.Enqueue(6);
queue.Enqueue(7);
queue.Dequeue();
queue.Dequeue();
queue.Print();
queue.GetUnderlyingArray().Print();
queue.Enqueue(8);
queue.Enqueue(9);
queue.Print();
queue.GetUnderlyingArray().Print();
queue.Enqueue(0);
queue.Enqueue(1);
queue.Print();
queue.GetUnderlyingArray().Print();
