namespace Trarizon.Library.Roslyn.SourceInfos.CSharp;
public static class CodeFactory
{
    public static string Literal(string value) => $"\"{value}\"";
    public static string LiteralUtf8(string value) => $"\"{value}\"u8";
    public static string Literal(bool value) => value ? "true" : "false";

    public static string AutoGeneratedTopCommentTrivia = "// <auto-generated />";

    /// <summary>
    /// <c>#pragma warning disable/restore {err-codes}</c>
    /// </summary>
    public static string PragmaWarningTrivia(bool restore, params string[] errorCodes)
        => $"#pragma warning {(restore ? "restore" : "disable")} {string.Join(", ", errorCodes)}";

    public static string GeneratedCodeAttributeList(string tool, string version)
        => $"[global::{KnownInfos.GeneratedCodeAttribute.TypeFullName}(\"{tool}\", \"{version}\")]";

    public static string InterceptsLocationAttributeList(string filePath, int line, int character)
        => $"[global::{KnownInfos.InterceptsLocationAttribute.TypeFullName}(\"{filePath}\", {line}, {character})]";
}
