// <auto-generated />

using System.Runtime.CompilerServices;
#if NET9_0_OR_GREATER

public static partial class TraDelegate
{
    // Actions

    public static unsafe Action<T1> Create<TObj, T1>(TObj obj, delegate*<TObj, T1, void> methodPtr) where TObj : class
        => Utils<T1>.CreateAction(obj, (nint)methodPtr);

    private static partial class Utils<T1>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        public static extern Action<T1> CreateAction(object obj, nint methodPtr);
    }

    public static unsafe Action<T1, T2> Create<TObj, T1, T2>(TObj obj, delegate*<TObj, T1, T2, void> methodPtr) where TObj : class
        => Utils<T1, T2>.CreateAction(obj, (nint)methodPtr);

    private static partial class Utils<T1, T2>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        public static extern Action<T1, T2> CreateAction(object obj, nint methodPtr);
    }

    public static unsafe Action<T1, T2, T3> Create<TObj, T1, T2, T3>(TObj obj, delegate*<TObj, T1, T2, T3, void> methodPtr) where TObj : class
        => Utils<T1, T2, T3>.CreateAction(obj, (nint)methodPtr);

    private static partial class Utils<T1, T2, T3>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        public static extern Action<T1, T2, T3> CreateAction(object obj, nint methodPtr);
    }

    public static unsafe Action<T1, T2, T3, T4> Create<TObj, T1, T2, T3, T4>(TObj obj, delegate*<TObj, T1, T2, T3, T4, void> methodPtr) where TObj : class
        => Utils<T1, T2, T3, T4>.CreateAction(obj, (nint)methodPtr);

    private static partial class Utils<T1, T2, T3, T4>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        public static extern Action<T1, T2, T3, T4> CreateAction(object obj, nint methodPtr);
    }

    // Funcs

    public static unsafe Func<TResult> Create<TObj, TResult>(TObj obj, delegate*<TObj, TResult> methodPtr) where TObj : class
        => Utils<TResult>.CreateFunc(obj, (nint)methodPtr);

    private static partial class Utils<T1>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)] public static extern Func<T1> CreateFunc(object obj, nint methodPtr);
    }

    public static unsafe Func<T1, TResult> Create<TObj, T1, TResult>(TObj obj, delegate*<TObj, T1, TResult> methodPtr) where TObj : class
        => Utils<T1, TResult>.CreateFunc(obj, (nint)methodPtr);

    private static partial class Utils<T1, T2>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)] public static extern Func<T1, T2> CreateFunc(object obj, nint methodPtr);
    }

    public static unsafe Func<T1, T2, TResult> Create<TObj, T1, T2, TResult>(TObj obj, delegate*<TObj, T1, T2, TResult> methodPtr) where TObj : class
        => Utils<T1, T2, TResult>.CreateFunc(obj, (nint)methodPtr);

    private static partial class Utils<T1, T2, T3>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)] public static extern Func<T1, T2, T3> CreateFunc(object obj, nint methodPtr);
    }

    public static unsafe Func<T1, T2, T3, TResult> Create<TObj, T1, T2, T3, TResult>(TObj obj, delegate*<TObj, T1, T2, T3, TResult> methodPtr) where TObj : class
        => Utils<T1, T2, T3, TResult>.CreateFunc(obj, (nint)methodPtr);

    private static partial class Utils<T1, T2, T3, T4>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)] public static extern Func<T1, T2, T3, T4> CreateFunc(object obj, nint methodPtr);
    }

    public static unsafe Func<T1, T2, T3, T4, TResult> Create<TObj, T1, T2, T3, T4, TResult>(TObj obj, delegate*<TObj, T1, T2, T3, T4, TResult> methodPtr) where TObj : class
        => Utils<T1, T2, T3, T4, TResult>.CreateFunc(obj, (nint)methodPtr);

    private static partial class Utils<T1, T2, T3, T4, T5>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)] public static extern Func<T1, T2, T3, T4, T5> CreateFunc(object obj, nint methodPtr);
    }

}

#endif
