<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>

    <Import Project="..\..\Nuget.props" />
    <PropertyGroup>
        <Version>1.1.0.13</Version>
        <Description>Trarizon's personal library</Description>
    </PropertyGroup>

    <!-- Reference -->

    <ItemGroup>
        <PackageReference Include="PolySharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="System.Threading.Tasks.Extensions" />
        <PackageReference Include="Microsoft.Bcl.Memory" />
        <PackageReference Include="System.Memory" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Trarizon.Library.Core\Trarizon.Library.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="TraDelegate.tt">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>TraDelegate.tt.g.cs</LastGenOutput>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="TraDelegate.tt.g.cs">
          <DesignTime>True</DesignTime>
          <AutoGen>True</AutoGen>
          <DependentUpon>TraDelegate.tt</DependentUpon>
        </Compile>
    </ItemGroup>

    <PropertyGroup Label="Polyfills">
        <PolySharpIncludeGeneratedTypes>
            System.Diagnostics.CodeAnalysis.ExperimentalAttribute;
            System.Runtime.CompilerServices.CallerArgumentExpressionAttribute;

            System.Diagnostics.CodeAnalysis.MaybeNullAttribute;
            System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute;

            System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute;
            System.Runtime.CompilerServices.IsExternalInit;
        </PolySharpIncludeGeneratedTypes>
    </PropertyGroup>

</Project>
