// <auto-generated />

#if OPTIONAL && NET9_0_OR_GREATER

namespace Trarizon.Library.Functional;

partial class RefOptional
{
    public static RefOptional<TResult> Bind<T, TMid, TResult>(this Optional<T> self, Func<T, Optional<TMid>> selector, Func<T, TMid, TResult> resultSelector)
        where TResult : allows ref struct
    {
        if (self.HasValue)
        {
            var mid = selector(self.Value);
            if (mid.HasValue)
                return new(resultSelector(self.Value, mid.Value));
        }
        return default;
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static RefOptional<TResult> SelectMany<T, TMid, TResult>(this Optional<T> self, Func<T, Optional<TMid>> selector, Func<T, TMid, TResult> resultSelector)
        where TResult : allows ref struct
        => Bind<T, TMid, TResult>(self, selector, resultSelector);

    public static RefOptional<TResult> Bind<T, TMid, TResult>(this Optional<T> self, Func<T, RefOptional<TMid>> selector, Func<T, TMid, TResult> resultSelector)
        where TMid : allows ref struct where TResult : allows ref struct
    {
        if (self.HasValue)
        {
            var mid = selector(self.Value);
            if (mid.HasValue)
                return new(resultSelector(self.Value, mid.Value));
        }
        return default;
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static RefOptional<TResult> SelectMany<T, TMid, TResult>(this Optional<T> self, Func<T, RefOptional<TMid>> selector, Func<T, TMid, TResult> resultSelector)
        where TMid : allows ref struct where TResult : allows ref struct
        => Bind<T, TMid, TResult>(self, selector, resultSelector);

    public static RefOptional<TResult> Bind<T, TMid, TResult>(this RefOptional<T> self, Func<T, Optional<TMid>> selector, Func<T, TMid, TResult> resultSelector)
        where T : allows ref struct where TResult : allows ref struct
    {
        if (self.HasValue)
        {
            var mid = selector(self.Value);
            if (mid.HasValue)
                return new(resultSelector(self.Value, mid.Value));
        }
        return default;
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static RefOptional<TResult> SelectMany<T, TMid, TResult>(this RefOptional<T> self, Func<T, Optional<TMid>> selector, Func<T, TMid, TResult> resultSelector)
        where T : allows ref struct where TResult : allows ref struct
        => Bind<T, TMid, TResult>(self, selector, resultSelector);

    public static RefOptional<TResult> Bind<T, TMid, TResult>(this RefOptional<T> self, Func<T, RefOptional<TMid>> selector, Func<T, TMid, TResult> resultSelector)
        where T : allows ref struct where TMid : allows ref struct where TResult : allows ref struct
    {
        if (self.HasValue)
        {
            var mid = selector(self.Value);
            if (mid.HasValue)
                return new(resultSelector(self.Value, mid.Value));
        }
        return default;
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static RefOptional<TResult> SelectMany<T, TMid, TResult>(this RefOptional<T> self, Func<T, RefOptional<TMid>> selector, Func<T, TMid, TResult> resultSelector)
        where T : allows ref struct where TMid : allows ref struct where TResult : allows ref struct
        => Bind<T, TMid, TResult>(self, selector, resultSelector);

}

#endif
