using System.Reflection;
using Trarizon.Library.Roslyn;
using Trarizon.Library.Roslyn.CSharp;

namespace Trarizon.Library.Generators;
public static class Literals
{
    public const string NS_Library = "Trarizon.Library";
    public const string Category = $"{NS_Library}.{nameof(Generators)}";

    public const string NS_CodeAnalysis = $"{NS_Library}.CodeAnalysis";
    public const string NS_CodeGeneration = $"{NS_Library}.CodeGeneration";

    public const string Code_AutoGenerated_TopTrivia = "// <auto-generated />";

    public static readonly string GeneratedCodeAttribute_Tool_Argument = Assembly.GetExecutingAssembly().GetName().Name;
    public static readonly string GeneratedCodeAttribute_Version_Argument = Assembly.GetExecutingAssembly().GetName().Version.ToString();
    public static readonly string Code_GeneratedCodeAttributeList = $"[{KnownLiterals.GeneratedCodeAttributeProxy.Code_Construct(GeneratedCodeAttribute_Tool_Argument, GeneratedCodeAttribute_Version_Argument)}]";

    public const string FriendAccessAnalyzer_Id = "00";
    public const string BackingFieldAccessAnalyzer_Id = "01";
    public const string ExternalSealedAnalyer_Id = "02";
    public const string SingletonGenerator_Id = "03";
}
