using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.CodeDom.Compiler;
using System.IO;
using System.Linq;
using Trarizon.Library.CodeAnalysis.SourceGeneration.Internal;
using Trarizon.Library.Roslyn;
using Trarizon.Library.Roslyn.Collections;
using Trarizon.Library.Roslyn.Emitting;
using Trarizon.Library.Roslyn.Extensions;
using Trarizon.Library.Roslyn.SourceInfos;
using Trarizon.Library.Roslyn.SourceInfos.Emitting;

namespace Trarizon.Library.CodeAnalysis.SourceGeneration;

[Generator(LanguageNames.CSharp)]
internal sealed class GenDisposingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var langVersion = context.ParseOptionsProvider.Select((opt, token) => ((CSharpParseOptions)opt).LanguageVersion);

        var datas = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Trarizon.Library.CodeAnalysis.Generation.GenDisposingAttribute",
            (node, ct) => node is TypeDeclarationSyntax,
            (context, ct) =>
            {
                if (context.TargetSymbol is not INamedTypeSymbol symbol)
                    return default;
                if (context.TargetNode is not TypeDeclarationSyntax syntax)
                    return default;
                if (context.Attributes is not [var attr])
                    return default;

                if (!context.SemanticModel.Compilation.TryGetTypeByMetadataName("System.IDisposable", out var disposableSymbol))
                    return default;

                bool useDisposeHelperMethod = symbol.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Any(Utils.IsDisposeMethod);

                var disposableFields = symbol.GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(f =>
                    {
                        var ty = f.Type;
                        if (ty.IsImplements(disposableSymbol))
                            return true;
                        if (ty.IsRefLikeType && ty.GetMembers().OfType<IMethodSymbol>().Any(Utils.IsDisposeMethod))
                            return true;
                        return false;
                    })
                    .Select(f =>
                    {
                        if (f.IsImplicitlyDeclared && f.AssociatedSymbol is IPropertySymbol prop)
                            return new DisposableMemberInfo(prop.Name, false);
                        return new DisposableMemberInfo(f.Name, false);
                    });

                return new Data(
                    symbol.ToFileNameString(),
                    TypeHierarchyInfo.Create(symbol, syntax),
                    symbol.IsRefLikeType,
                    attr.GetNamedArgument("Explicitly").GetConstantValueOrDefault<bool>(),
                    useDisposeHelperMethod,
                    disposableFields.ToSequenceEquatableImmutableArray()
                    );
            })
            .OfNotNull();

        context.RegisterSourceOutput(datas.Collect().Combine(langVersion), (context, src) =>
        {
            var (data, langVer) = src;

            if (data.SelectMany(x => x.DisposableMembers).Any(x => !x.IsImplicitImplemented)) {
                using var sw = new StringWriter();
                using var writer = new IndentedTextWriter(sw);
                sw.WriteLine("// <auto-generated />");
                writer.WriteLine();
                writer.WriteLine($"namespace {Codes.NamespaceGenerated}");
                using (writer.EnterBracketIndentScope('{')) {
                    writer.WriteLine("internal static class GenDisposingHelpers");
                    using (writer.EnterBracketIndentScope('{')) {
                        writer.WriteLine("public static void Dispose<T>(T disposable)");
                        if (langVer >= LanguageVersion.CSharp13) {
                            writer.Indent++;
                            using (var scope = writer.EmitCSharpPreprocessorConditional("NET9_0_OR_GREATER")) {
                                writer.WriteLine("where T : global::System.IDisposable, allows ref struct");
                                scope.EmitElse();
                                writer.WriteLine("where T : global::System.IDisposable");
                            }
                            writer.Indent--;
                        }
                        using (writer.EnterBracketIndentScope('{')) {
                            writer.WriteLine("disposable.Dispose();");
                        }
                    }
                }
                context.AddSource("GenDisposingHelpers.g.internal.cs", sw.ToString());
            }
        });

        context.RegisterSourceOutput(datas.Combine(langVersion), (context, src) =>
        {
            var (data, langVer) = src;

            if (data.DisposableMembers.Length == 0)
                return;

            using var sw = new StringWriter();
            using var writer = new IndentedTextWriter(sw);

            writer.WriteLine("// <auto-generated />");
            writer.WriteLine();

            using (writer.EmitCSharpTypeHierarchy(data.TypeHierarchy, partial: true, (writer, info) =>
            {
                writer.WriteLine($"partial {info.Keywords} {info.Name}");
                if (data.IsRefLikeType) {
                    if (langVer >= LanguageVersion.CSharp13) {
                        using (writer.EmitCSharpPreprocessorConditional("NET9_0_OR_GREATER")) {
                            writer.WriteLine("    : global::System.IDisposable");
                        }
                    }
                }
                else {
                    writer.WriteLine("    : global::System.IDisposable");
                }
            })) {
                if (data.UseDisposeHelperMethod) {
                    writer.WriteMultipleLines($"""
                        /// <summary>
                        /// Disposes all disposable members.
                        /// <list type="bullet">
                        {string.Join("\n", data.DisposableMembers.Select(m => $"/// <item>{m.MemberName}</item>"))}
                        /// </list>
                        /// </summary>
                        """);
                    writer.WriteLine("private void DisposeDisposableMembers()");
                }
                else if (data.Explicitly)
                    writer.WriteLine("void global::System.IDisposable.Dispose()");
                else
                    writer.WriteLine("public void Dispose()");

                using (writer.EnterBracketIndentScope('{')) {
                    foreach (var member in data.DisposableMembers) {
                        if (member.IsImplicitImplemented) {
                            writer.WriteLine($"this.{member.MemberName}?.Dispose();");
                        }
                        else {
                            writer.WriteLine($"if (this.{member.MemberName} is not null)");
                            writer.WriteLine($"    global::{Codes.NamespaceGenerated}.GenDisposingHelpers.Dispose(this.{member.MemberName});");
                        }
                    }
                }
            }

            context.AddSource($"{data.GeneratedFileName}.g.cs", sw.ToString());
        });
    }
    private sealed record class Data(
        string GeneratedFileName,
        TypeHierarchyInfo TypeHierarchy,
        bool IsRefLikeType,
        bool Explicitly,
        bool UseDisposeHelperMethod,
        SequenceEquatableImmutableArray<DisposableMemberInfo> DisposableMembers);

    private sealed record class DisposableMemberInfo(
        string MemberName,
        bool IsImplicitImplemented);

    private static class Utils
    {
        public static bool IsDisposeMethod(IMethodSymbol symbol)
        {
            return symbol.Name == "Dispose" && symbol.Parameters.Length == 0 && symbol.ReturnsVoid;
        }
    }
}
