using System.CodeDom.Compiler;
using Trarizon.Library.Roslyn.CSharp;

namespace Trarizon.Library.Functional.Generators;

internal static class Utils
{
    public static readonly string GeneratedCodeAttributeList = CodeFactory.GeneratedCodeAttributeList(
        typeof(Utils).Assembly.GetName().Name,
        typeof(Utils).Assembly.GetName().Version.ToString()
    );
    public const string AggressiveInliningAttributeList = "[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]";
    public const string UnscopedRefAttributeList = "[global::System.Diagnostics.CodeAnalysis.UnscopedRef]";

    public const string AutoGeneratedTopTrivia = "// <auto-generated>";
    public const string NullableEnableTrivia = "#nullable enable";

    public static IEnumerable<T> JoinWriteEmptyLine<T>(this IEnumerable<T> source, TextWriter writer)
    {
        using var enumerator = source.GetEnumerator();
        if (!enumerator.MoveNext())
            yield break;
        var current = enumerator.Current;
        while (enumerator.MoveNext())
        {
            yield return current;
            writer.WriteLine();
            current = enumerator.Current;
        }
        yield return current;
    }

    public static string JoinToString<T>(this IEnumerable<T> source, Func<T, string> toString, string separator)
    {
        return string.Join(separator, source.Select(toString));
    }

    public static string JoinToString<T>(this IEnumerable<T> source, string separator)
    {
        return string.Join(separator, source);
    }
}
