// <auto-generated />

using System.Collections.Generic;
using System.Collections.Immutable;
using Trarizon.Library.Roslyn.Collections;

namespace Trarizon.Library.Roslyn;
public static partial class PiplineEqualityHelpers
{
}