using System.CodeDom.Compiler;
using Trarizon.Library.Roslyn.CSharp;
using Trarizon.Library.Roslyn.Emitting;

namespace Trarizon.Library.Functional.Generators.TypeUnion;

partial class TypeUnionGenerator
{
    public const string PointerHelperFQName = "global::Trarizon.Library.Functional.Generated.__PointerHelper";
    public const string VoidPointerHelperFQName = "global::Trarizon.Library.Functional.Generated.__VoidPointerHelper";

    private string GetPointeHelperDeclaration()
    {
        return $$"""
        namespace Trarizon.Library.Functional.Generated
        {
            {{Utils.GeneratedCodeAttributeList}}
            internal struct __PointerHelper<T> { public unsafe T* Pointer; }
        
            {{Utils.GeneratedCodeAttributeList}}
            internal struct __VoidPointerHelper { public unsafe void* Pointer; }
        }
        """;
    }

    private void EmitTypeUnion(IndentedTextWriter writer, TypeUnionData data, (bool MaybeNull, bool UnscopedRef) env)
    {
        var refLike = data.Variants.Any(x => x.IsRefLikeType) ? "ref " : "";

        writer.EmitAutoGeneratedTopTrivia();
        writer.WriteLine();
        writer.EmitNullableEnableTrivia();
        writer.WriteLine(CodeFactory.PragmaWarningTrivia(false, "CS8618", "CS8500"));

        writer.WriteLine();

        using (writer.EmitCSharpTypeHierarchy(data.TypeHierarchy.Parent, partial: true))
        {
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteLine($"{refLike}partial {data.TypeHierarchy.Keywords} {data.TypeHierarchy.Name}");

            using (writer.EnterBracketIndentScope('{'))
            {
                EmitFields(writer, data);
                writer.WriteLine();
                EmitNullProperty(writer, data);
                writer.WriteLine();
                EmitConstructors(writer, data);
                writer.WriteLine();
                EmitAsMethod(writer, data);
                writer.WriteLine();
                EmitAsExactlyMethod(writer, data);
                writer.WriteLine();
                EmitIsMethod(writer, data);
                writer.WriteLine();
                EmitIsExactlyMethod(writer, data);
                writer.WriteLine();
                writer.WriteLine("// -- DangerousGetValues --");
                writer.WriteLine();
                EmitDangerousGetValueMethods(writer, data, env.UnscopedRef);
                writer.WriteLine();
                EmitUnmanagedStructType(writer, data);
            }
        }
    }

    private void EmitFields(IndentedTextWriter writer, TypeUnionData data)
    {
        // __um_fieldName // union_member
        writer.WriteLine($"private readonly uint __um_flag;");

        if (data.Variants.Any(x => x.TypeKind is VariantTypeKind.Reference))
        {
            writer.WriteLine($"private readonly object __um_obj;");
        }
        foreach (var variant in data.Variants.Where(x => x.TypeKind is VariantTypeKind.Managed))
        {
            writer.WriteLine($"private readonly {variant.TypeFQName} __um_managed{variant.FieldId};");
        }
        if (data.Variants.Any(x => x.TypeKind.IsUnmanaged()))
        {
            writer.WriteLine($"private readonly __ut_Unmanaged __um_unmanaged;");
        }
    }

    private void EmitConstructors(IndentedTextWriter writer, TypeUnionData data)
    {
        foreach (var variant in data.Variants.JoinWriteEmptyLine(writer))
        {
            var @unsafe = variant.TypeKind is VariantTypeKind.Pointer ? "unsafe " : "";
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public {{@unsafe}}{{data.TypeHierarchy.Name}}({{variant.TypeFQName}} value)
                {
                    this.__um_flag = {{variant.Id}}u;
                    {{ExprVariantFieldAccess(variant)}} = value;
                }
                """);
        }
    }

    private void EmitNullProperty(IndentedTextWriter writer, TypeUnionData data)
    {
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine("public bool IsNull { get { return this.__um_flag == 0u; } }");
    }

    private void EmitAsMethod(IndentedTextWriter writer, TypeUnionData data)
    {
        // Here T wont be pointer, as C# not allowed

        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public T? As<T>()");
        using (writer.EnterBracketIndentScope('{'))
        {
            writer.WriteLine("switch(this.__um_flag)");
            using (writer.EnterBracketIndentScope('{'))
            {
                foreach (var variant in data.Variants)
                {
                    if (variant.TypeKind is VariantTypeKind.Pointer)
                        continue;

                    writer.WriteMultipleLines($$"""
                        case {{variant.Id}}u:
                        {
                            if (typeof(T) == typeof({{variant.TypeFQName}}))
                            {
                                return {{ExprVariantToT(variant)}};
                            }
                            if ({{ExprVariantToT(variant)}} is T typed)
                            {
                                return typed;
                            }
                            break;
                        }
                        """);
                }
            }
            writer.WriteLine("return default(T);");
        }
    }

    private void EmitAsExactlyMethod(IndentedTextWriter writer, TypeUnionData data)
    {
        // Here T wont be pointer, as C# not allowed

        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public T? AsExactly<T>()");
        using (writer.EnterBracketIndentScope('{'))
        {
            foreach (var variant in data.Variants)
            {
                if (variant.TypeKind is VariantTypeKind.Pointer)
                    continue;

                writer.WriteMultipleLines($$"""
                    if (typeof(T) == typeof({{variant.TypeFQName}}))
                    {
                        if (this.__um_flag == {{variant.Id}}u)
                        {
                            return {{ExprVariantToT(variant)}};
                        }
                    }
                    """);
            }
            writer.WriteLine("return default(T);");
        }
    }

    private void EmitIsMethod(IndentedTextWriter writer, TypeUnionData data)
    {
        // Here T wont be pointer, as C# not allowed

        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public bool Is<T>()");
        using (writer.EnterBracketIndentScope('{'))
        {
            writer.WriteLine("switch(this.__um_flag)");
            using (writer.EnterBracketIndentScope('{'))
            {
                foreach (var variant in data.Variants)
                {
                    if (variant.TypeKind is VariantTypeKind.Pointer)
                        continue;

                    writer.WriteMultipleLines($$"""
                        case {{variant.Id}}u:
                        {
                            if (typeof(T) == typeof({{variant.TypeFQName}}))
                            {
                                return true;
                            }
                            return {{ExprVariantToT(variant)}} is T;
                        }
                        """);
                }
            }
            writer.WriteLine("return false;");
        }
    }

    private void EmitIsExactlyMethod(IndentedTextWriter writer, TypeUnionData data)
    {
        // Here T wont be pointer, as C# not allowed

        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public bool IsExactly<T>()");
        using (writer.EnterBracketIndentScope('{'))
        {
            foreach (var variant in data.Variants)
            {
                if (variant.TypeKind is VariantTypeKind.Pointer)
                    continue;

                writer.WriteMultipleLines($$"""
                    if (typeof(T) == typeof({{variant.TypeFQName}}))
                    {
                        return this.__um_flag == {{variant.Id}}u;
                    }
                    """);
            }
            writer.WriteLine("return false;");
        }
    }

    private void EmitUnmanagedStructType(IndentedTextWriter writer, TypeUnionData data)
    {
        writer.WriteLine($"[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]");
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine("private struct __ut_Unmanaged");
        using (writer.EnterBracketIndentScope('{'))
        {
            foreach (var variant in data.Variants.Where(v => v.TypeKind.IsUnmanaged()))
            {
                var @unsafe = variant.TypeKind is VariantTypeKind.Pointer ? "unsafe " : "";
                writer.WriteLine($"[global::System.Runtime.InteropServices.FieldOffset(0)]");
                writer.WriteLine($"public {@unsafe}{variant.FieldTypeFQName} _{variant.FieldId};");
            }
        }
    }

    private void EmitDangerousGetValueMethods(IndentedTextWriter writer, TypeUnionData data, bool hasUnscopedRef)
    {
        // Reference
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine(Utils.AggressiveInliningAttributeList);
        if (hasUnscopedRef)
            writer.WriteLine(Utils.UnscopedRefAttributeList);
        writer.WriteLine($"private ref readonly T DangerousGetReferenceTypeValue<T>()");
        using (writer.EnterBracketIndentScope('{'))
        {
            writer.WriteLine($"return ref global::System.Runtime.CompilerServices.Unsafe.As<object, T>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<object>(in this.__um_obj));");
        }

        writer.WriteLine();

        // unmanaged
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine(Utils.AggressiveInliningAttributeList);
        if (hasUnscopedRef)
            writer.WriteLine(Utils.UnscopedRefAttributeList);
        writer.WriteLine($"private ref readonly T DangerousGetUnmanagedValueTypeValue<T>()");
        using (writer.EnterBracketIndentScope('{'))
        {
            writer.WriteLine($"return ref global::System.Runtime.CompilerServices.Unsafe.As<__ut_Unmanaged, T>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<__ut_Unmanaged>(in this.__um_unmanaged));");
        }

        writer.WriteLine();

        // managed
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine(Utils.AggressiveInliningAttributeList);
        if (hasUnscopedRef)
            writer.WriteLine(Utils.UnscopedRefAttributeList);
        writer.WriteLine($"private ref readonly T DangerousGetManagedValueTypeValue<T>()");
        using (writer.EnterBracketIndentScope('{'))
        {
            foreach (var item in data.Variants.Where(x => x.TypeKind is VariantTypeKind.Managed))
            {
                writer.WriteMultipleLines($$"""
                    if (typeof(T) == typeof({{item.TypeFQName}}))
                        return ref {{ExprVariantToT(item)}};
                    """);
            }
            writer.WriteLine("return ref global::System.Runtime.CompilerServices.Unsafe.NullRef<T>();");
        }

        writer.WriteLine();

        // pointer
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine(Utils.AggressiveInliningAttributeList);
        if (hasUnscopedRef)
            writer.WriteLine(Utils.UnscopedRefAttributeList);
        writer.WriteLine($"private unsafe ref readonly T* DangerousGetPointerTypeValue<T>()");
        using (writer.EnterBracketIndentScope('{'))
        {
            writer.WriteLine($"return ref global::System.Runtime.CompilerServices.Unsafe.As<__ut_Unmanaged, global::Trarizon.Library.Functional.Generated.__PointerHelper<T>>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<__ut_Unmanaged>(in this.__um_unmanaged)).Pointer;");
        }

        writer.WriteLine();

        // void*
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine(Utils.AggressiveInliningAttributeList);
        if (hasUnscopedRef)
            writer.WriteLine(Utils.UnscopedRefAttributeList);
        writer.WriteLine($"private unsafe ref readonly void* DangerousGetVoidPointerTypeValue()");
        using (writer.EnterBracketIndentScope('{'))
        {
            writer.WriteLine($"return ref global::System.Runtime.CompilerServices.Unsafe.As<__ut_Unmanaged, global::Trarizon.Library.Functional.Generated.__VoidPointerHelper>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<__ut_Unmanaged>(in this.__um_unmanaged)).Pointer;");
        }
    }

    private string ExprVariantFieldAccess(VariantData variant, string @this = "this")
    {
        return variant.TypeKind switch
        {
            VariantTypeKind.Pointer => $"{@this}.__um_unmanaged._{variant.FieldId}.Pointer",
            VariantTypeKind.Unmanaged => $"{@this}.__um_unmanaged._{variant.FieldId}",
            VariantTypeKind.Reference => $"{@this}.__um_obj",
            VariantTypeKind.Managed => $"{@this}.__um_managed{variant.FieldId}",
            _ => throw new NotImplementedException(),
        };
    }

    private string ExprVariantToT(VariantData variant, string targetType = "T")
    {
        var fieldFullyQualifiedTypeName = variant.TypeKind switch
        {
            VariantTypeKind.Reference => "object",
            _ => variant.TypeFQName,
        };
        return $"global::System.Runtime.CompilerServices.Unsafe.As<{fieldFullyQualifiedTypeName}, {targetType}>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<{fieldFullyQualifiedTypeName}>(in {ExprVariantFieldAccess(variant)}))";
    }
}
