using System.CodeDom.Compiler;
using Trarizon.Library.Roslyn.CSharp;
using Trarizon.Library.Roslyn.Emitting;

namespace Trarizon.Library.Functional.Generators.TypeUnion;

partial class TypeUnionGenerator
{
    private void EmitTypeUnion(IndentedTextWriter writer, TypeUnionData data, Env env)
    {
        var refLike = data.Variants.Any(x => x.TypeData.IsRefLikeType) ? "ref " : "";

        writer.WriteLine(Utils.AutoGeneratedTopTrivia);
        writer.WriteLine();
        writer.WriteLine(Utils.NullableEnableTrivia);
        writer.WriteLine(CodeFactory.PragmaWarningTrivia(false, "CS8618", "CS8500"));
        writer.WriteLine();
        writer.WriteLine("// enabled features:");
        if (env.AllowsRefStruct)
            writer.WriteLine("// allows ref struct constraint");
        if (env.UnscopedRef)
            writer.WriteLine("// UnscopedRefAttribute");

        writer.WriteLine();

        using (writer.EmitCSharpTypeHierarchy(data.TypeHierarchy.Parent, partial: true))
        {
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteLine($"[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]");
            writer.WriteLine($"{refLike}partial {data.TypeHierarchy.Keywords} {data.TypeHierarchy.Name}");

            using (writer.EnterBracketIndentScope('{'))
            {
                EmitFields(writer, data);
                writer.WriteLine();
                EmitNullProperty(writer, data);
                writer.WriteLine();
                EmitConstructors(writer, data);
                writer.WriteLine();

                writer.WriteLineNoTabs("#region As");
                writer.WriteLine();
                EmitAsMethod(writer, data, env);
                writer.WriteLine();
                EmitAsExactlyMethod(writer, data, env);
                writer.WriteLine();
                writer.WriteLineNoTabs("#endregion");
                writer.WriteLine();

                writer.WriteLineNoTabs("#region Is");
                writer.WriteLine();
                EmitIsMethod(writer, data, env);
                writer.WriteLine();
                EmitIsExactlyByParameterMethod(writer, data);
                writer.WriteLine();
                EmitIsExactlyMethod(writer, data, env);
                writer.WriteLine();
                writer.WriteLineNoTabs("#endregion");
                writer.WriteLine();

                writer.WriteLineNoTabs("#region DangerousGetValueRef");
                writer.WriteLine();
                EmitDangerousGetValueMethods(writer, data, env);
                writer.WriteLine();
                writer.WriteLineNoTabs("#endregion");
                writer.WriteLine();
                EmitUnmanagedStructType(writer, data);
            }
        }
    }

    private void EmitFields(IndentedTextWriter writer, TypeUnionData data)
    {
        // __um_fieldName // union_member
        writer.WriteLine($"private readonly uint __um_flag;");

        if (data.Variants.Any(x => x.TypeData.TypeKind is VariantTypeKind.Reference))
        {
            writer.WriteLine($"private readonly object __um_obj;");
        }
        foreach (var variant in data.Variants.Where(x => x.TypeData.TypeKind is VariantTypeKind.Managed))
        {
            writer.WriteLine($"private readonly {variant.TypeData.FullyQName} __um_managed{variant.FieldId};");
        }
        if (data.Variants.Any(x => x.TypeData.TypeKind.IsUnmanaged))
        {
            writer.WriteLine($"private readonly __ut_Unmanaged __um_unmanaged;");
        }
    }

    private void EmitConstructors(IndentedTextWriter writer, TypeUnionData data)
    {
        foreach (var variant in data.Variants.Where(x => x.TypeData.TypeKind is not VariantTypeKind.Void).JoinWriteEmptyLine(writer))
        {
            var @unsafe = variant.TypeData.TypeKind.IsPointer ? "unsafe " : "";
            var cast = variant.TypeData.TypeKind.IsPointer ? $"(global::System.IntPtr)" : "";
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public {{@unsafe}}{{data.TypeHierarchy.Name}}({{variant.TypeData.FullyQName}} value)
                {
                    this.__um_flag = {{variant.Id}}u;
                    {{ExprVariantFieldAccess(variant)}} = {{cast}}value;
                }
                """);
        }
    }

    private void EmitNullProperty(IndentedTextWriter writer, TypeUnionData data)
    {
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine("public bool IsNull { get { return this.__um_flag == 0u; } }");
    }

    // emit: As

    private void EmitAsMethod(IndentedTextWriter writer, TypeUnionData data, Env env)
    {
        var @allows = env.AllowsRefStruct ? " where T : allows ref struct" : "";

        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public readonly T? As<T>(){@allows}");
        using (writer.EnterBracketIndentScope('{'))
        {
            writer.WriteLine("switch(this.__um_flag)");
            using (writer.EnterBracketIndentScope('{'))
            {
                foreach (var variant in data.Variants.Where(x => x.TypeData.TypeKind.IsGenericable))
                {
                    if (env.AllowsRefStruct || !variant.TypeData.IsRefLikeType)
                    {
                        writer.WriteLine($"case {variant.Id}u:");
                        using (writer.EnterBracketIndentScope('{'))
                        {
                            writer.WriteLine($"if (typeof(T) == typeof({variant.TypeData.FullyQName}))");
                            writer.WriteLine($"    return {ExprVariantToT(variant)};");
                            if (!variant.TypeData.IsRefLikeType)
                            {
                                writer.WriteLine($"if ({ExprVariantToT(variant, variant.TypeData.FullyQName)} is T typed)");
                                writer.WriteLine($"    return typed;");
                            }
                            writer.WriteLine("break;");
                        }
                    }
                }
            }
            writer.WriteLine("return default(T);");
        }
    }

    private void EmitAsExactlyMethod(IndentedTextWriter writer, TypeUnionData data, Env env)
    {
        var @allows = env.AllowsRefStruct ? " where T : allows ref struct" : "";

        writer.WriteMultipleLines(DocCommentAsExactly("<typeparamref name=\"T\"/>", code: false));
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public readonly T? AsExactly<T>(){@allows}");
        using (writer.EnterBracketIndentScope('{'))
        {
            foreach (var variant in data.Variants.Where(x => x.TypeData.TypeKind.IsGenericable))
            {
                if (env.AllowsRefStruct || !variant.TypeData.IsRefLikeType)
                {
                    writer.WriteMultipleLines($$"""
                        if (typeof(T) == typeof({{variant.TypeData.FullyQName}}))
                        {
                            if (this.__um_flag == {{variant.Id}}u)
                                return {{ExprVariantToT(variant)}};
                        }
                        """);
                }
            }

            writer.WriteLine("return default(T);");
        }

        // ref struct

        if (!env.AllowsRefStruct)
        {
            // For old runtime, emit specialized method for ref-like type
            foreach (var variant in data.Variants.Where(x => x.TypeData.IsRefLikeType))
            {
                // variant is ref struct, so possible type kind is Managed or Unmanaged

                writer.WriteLine();
                writer.WriteMultipleLines(DocCommentAsExactly(variant.TypeData.MinimalQName));
                writer.WriteLine(Utils.GeneratedCodeAttributeList);
                writer.WriteMultipleLines($$"""
                    public readonly {{variant.TypeData.FullyQName}} As_{{variant.ReadableIdentifier}}()
                    {
                        if (this.__um_flag == {{variant.Id}}u)
                            return {{ExprVariantToT(variant, variant.TypeData.FullyQName)}};
                        return default({{variant.TypeData.FullyQName}});
                    }
                    """);
            }
        }

        // delegate*<>

        foreach(var variant in data.Variants.Where(x=>x.TypeData.TypeKind is VariantTypeKind.FunctionPointer))
        {
            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentAsExactly(variant.TypeData.MinimalQName));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public unsafe readonly {{variant.TypeData.FullyQName}} AsFunctionPointer_{{variant.ReadableIdentifier}}()
                {
                    if (this.__um_flag == {{variant.Id}}u)
                        return {{ExprVariantToT(variant, variant.TypeData.FullyQName)}};
                    return default({{variant.TypeData.FullyQName}});
                }
                """);
        }


        // T*

        var nonVoidPointers = data.Variants
            .Where(x => x.TypeData.IsNonVoidPointer)
            .GroupBy(x => x.TypeData.PointerLevel);

        foreach (var group in nonVoidPointers)
        {
            var stars = new string('*', group.Key);
            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentAsExactly($"T{stars}"));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteLine($"public unsafe readonly T{stars} AsPointer{(group.Key <= 1 ? "" : $"{group.Key}")}<T>(){@allows}");
            using (writer.EnterBracketIndentScope('{'))
            {
                foreach (var variant in group)
                {
                    if (env.AllowsRefStruct || !variant.TypeData.FinalPointerAtType.IsRefLikeType)
                    {
                        writer.WriteMultipleLines($$"""
                            if (typeof(T{{stars}}) == typeof({{variant.TypeData.FullyQName}}))
                            {
                                if (this.__um_flag == {{variant.Id}}u)
                                    return {{ExprVariantToT(variant)}};
                            }
                            """);
                    }
                }
                writer.WriteLine($"return default(T{stars});");
            }
        }

        // void*

        foreach (var group in data.Variants.Where(x => x.TypeData.IsVoidPointer))
        {
            var stars = new string('*', group.TypeData.PointerLevel);
            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentAsExactly($"void{stars}"));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public unsafe readonly void{{stars}} AsVoidPointer{{(group.TypeData.PointerLevel <= 1 ? "" : $"{group.TypeData.PointerLevel}")}}()
                {
                    if (this.__um_flag == {{group.Id}}u)
                        return {{ExprVariantToT(group, "void*")}};
                    return default(void{{stars}});
                }
                """);
        }

        // ref struct*

        if (!env.AllowsRefStruct)
        {
            // for old runtime, emit specialized method of ref-like type pointer
            foreach (var variant in data.Variants.Where(x => x.TypeData.IsNonVoidPointer && x.TypeData.FinalPointerAtType.IsRefLikeType))
            {
                var pointerLevel = variant.TypeData.PointerLevel <= 1 ? "" : $"{variant.TypeData.PointerLevel}";
                // variant is ref struct, so possible type kind is Managed or Unmanaged
                writer.WriteLine();
                writer.WriteMultipleLines(DocCommentAsExactly(variant.TypeData.MinimalQName));
                writer.WriteLine(Utils.GeneratedCodeAttributeList);
                writer.WriteMultipleLines($$"""
                    public unsafe readonly {{variant.TypeData.FullyQName}} AsPointer{{pointerLevel}}_{{variant.ReadableIdentifier}}()
                    {
                        if (this.__um_flag == {{variant.Id}}u)
                            return {{ExprVariantToT(variant, variant.TypeData.FullyQName)}};
                        return default({{variant.TypeData.FullyQName}});
                    }
                    """);
            }
        }

        // delegate*<>*

        foreach(var variant in data.Variants.Where(x=>x.TypeData.IsNonVoidPointer && x.TypeData.FinalPointerAtType.TypeKind is VariantTypeKind.FunctionPointer))
        {
            var pointerLevel=variant.TypeData.PointerLevel <=1 ? "" : $"{variant.TypeData.PointerLevel}";

            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentAsExactly(variant.TypeData.MinimalQName));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public unsafe readonly {{variant.TypeData.FullyQName}} AsPointer{{pointerLevel}}ToFunctionPointer_{{variant.ReadableIdentifier}}()
                {
                    if (this.__um_flag == {{variant.Id}}u)
                        return {{ExprVariantToT(variant, variant.TypeData.FullyQName)}};
                    return defalut({{variant.TypeData.FullyQName}});
                }
                """);
        }
    }

    // emit: Is

    private void EmitIsMethod(IndentedTextWriter writer, TypeUnionData data, Env env)
    {
        var @allows = env.AllowsRefStruct ? " where T : allows ref struct" : "";

        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public readonly bool Is<T>(){@allows}");
        using (writer.EnterBracketIndentScope('{'))
        {
            writer.WriteLine("switch(this.__um_flag)");
            using (writer.EnterBracketIndentScope('{'))
            {
                foreach (var variant in data.Variants.Where(x => x.TypeData.TypeKind.IsGenericable))
                {
                    if (env.AllowsRefStruct || !variant.TypeData.IsRefLikeType)
                    {
                        writer.WriteLine($"case {variant.Id}u:");
                        using (writer.EnterBracketIndentScope('{'))
                        {
                            writer.WriteLine($"if (typeof(T) == typeof({variant.TypeData.FullyQName}))");
                            writer.WriteLine($"    return true;");
                            if (!variant.TypeData.IsRefLikeType)
                            {
                                writer.WriteLine($"return {ExprVariantToT(variant, variant.TypeData.FullyQName)} is T;");
                            }
                            else
                            {
                                writer.WriteLine($"return false;");
                            }
                        }
                    }
                }
            }
            writer.WriteLine("return false;");
        }
    }

    private void EmitIsExactlyByParameterMethod(IndentedTextWriter writer, TypeUnionData data)
    {
        // by Type

        writer.WriteMultipleLines(DocCommentIsExactly(@"<paramref name=""type""/>", code: false));
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public readonly bool IsExactly(global::System.Type type)");
        using (writer.EnterBracketIndentScope('{'))
        {
            foreach (var variant in data.Variants)
            {
                writer.WriteMultipleLines($$"""
                    if (typeof({{variant.TypeData.FullyQName}}) == type)
                        return this.__um_flag == {{variant.Id}}u;
                    """);
            }
            writer.WriteLine("return false;");
        }
    }

    private void EmitIsExactlyMethod(IndentedTextWriter writer, TypeUnionData data, Env env)
    {
        var @allows = env.AllowsRefStruct ? " where T : allows ref struct" : "";

        writer.WriteMultipleLines(DocCommentIsExactly(@"<typeparamref name=""T""/>", code: false));
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"public readonly bool IsExactly<T>(){@allows}");
        using (writer.EnterBracketIndentScope('{'))
        {
            foreach (var variant in data.Variants.Where(x => x.TypeData.TypeKind.IsGenericable))
            {
                if (env.AllowsRefStruct || !variant.TypeData.IsRefLikeType)
                {
                    writer.WriteMultipleLines($$"""
                        if (typeof(T) == typeof({{variant.TypeData.FullyQName}}))
                            return this.__um_flag == {{variant.Id}}u;
                        """);
                }
            }
            writer.WriteLine("return false;");
        }

        // void

        if (data.Variants.FirstOrDefault(x => x.TypeData.TypeKind is VariantTypeKind.Void) is { } voidVariant)
        {
            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentIsExactly("void"));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public readonly bool IsVoid()
                {
                    return this.__um_flag == {{voidVariant.Id}}u;
                }
                """);
        }

        // ref struct

        if (!env.AllowsRefStruct)
        {
            foreach (var variant in data.Variants.Where(x => x.TypeData.IsRefLikeType))
            {
                writer.WriteLine();
                writer.WriteMultipleLines(DocCommentIsExactly(variant.TypeData.MinimalQName));
                writer.WriteLine(Utils.GeneratedCodeAttributeList);
                writer.WriteMultipleLines($$"""
                    public readonly bool Is_{{variant.ReadableIdentifier}}()
                    {
                        return this.__um_flag == {{variant.Id}}u;
                    }
                    """);
            }
        }

        // delegate*<>

        foreach(var variant in data.Variants.Where(x=>x.TypeData.TypeKind is VariantTypeKind.FunctionPointer))
        {
            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentIsExactly(variant.TypeData.MinimalQName));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public unsafe readonly bool IsFunctionPointer_{{variant.ReadableIdentifier}}()
                {
                    return this.__um_flag == {{variant.Id}}u;
                }
                """);
        }

        // T*

        var nonVoidPointers = data.Variants
            .Where(x => x.TypeData.IsNonVoidPointer)
            .GroupBy(x => x.TypeData.PointerLevel);

        foreach (var group in nonVoidPointers)
        {
            var stars = new string('*', group.Key);
            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentIsExactly($"T{stars}"));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteLine($"public unsafe readonly bool IsPointer{(group.Key <= 1 ? "" : $"{group.Key}")}<T>(){@allows}");
            using (writer.EnterBracketIndentScope('{'))
            {
                foreach (var variant in group)
                {
                    if (env.AllowsRefStruct || !variant.TypeData.FinalPointerAtType.IsRefLikeType)
                    {
                        writer.WriteLine($"if (typeof(T{stars}) == typeof({variant.TypeData.FullyQName}))");
                        writer.WriteLine($"    return this.__um_flag == {variant.Id}u;");
                    }
                }
                writer.WriteLine($"return false;");
            }
        }

        // void*

        foreach (var group in data.Variants.Where(x => x.TypeData.IsVoidPointer))
        {
            var stars = new string('*', group.TypeData.PointerLevel);
            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentIsExactly($"void{stars}"));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public unsafe readonly bool IsVoidPointer{{(group.TypeData.PointerLevel <= 1 ? "" : $"{group.TypeData.PointerLevel}")}}()
                {
                    return this.__um_flag == {{group.Id}}u;
                }
                """);
        }

        // ref struct*

        if (!env.AllowsRefStruct)
        {
            foreach (var variant in data.Variants.Where(x => x.TypeData.IsNonVoidPointer && x.TypeData.IsRefLikeType))
            {
                var ptrLv = variant.TypeData.PointerLevel <= 1 ? "" : $"{variant.TypeData.PointerLevel}";
                writer.WriteLine();
                writer.WriteMultipleLines(DocCommentIsExactly(variant.TypeData.MinimalQName));
                writer.WriteLine(Utils.GeneratedCodeAttributeList);
                writer.WriteMultipleLines($$"""
                    public unsafe readonly bool IsPointer{{ptrLv}}_{{variant.ReadableIdentifier}}()
                    {
                        return this.__um_flag == {{variant.Id}}u;
                    }
                    """);
            }
        }

        // delegate*<>*

        foreach(var variant in data.Variants.Where(x=>x.TypeData.IsNonVoidPointer && x.TypeData.TypeKind is VariantTypeKind.FunctionPointer))
        {
            var ptrLv=variant.TypeData.PointerLevel <= 1 ? "" : $"{variant.TypeData.PointerLevel}";
            writer.WriteLine();
            writer.WriteMultipleLines(DocCommentIsExactly(variant.TypeData.MinimalQName));
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteMultipleLines($$"""
                public unsafe readonly bool IsPointer{{ptrLv}}ToFunctionPointer_{{variant.ReadableIdentifier}}()
                {
                    return this.__um_flag == {{variant.Id}}u;
                }
                """);
        }
    }

    // emit: Unmanaged struct

    private void EmitUnmanagedStructType(IndentedTextWriter writer, TypeUnionData data)
    {
        var @ref = data.Variants.Any(x => x.TypeData.TypeKind.IsUnmanaged && x.TypeData.IsRefLikeType) ? "ref " : "";

        writer.WriteLine($"[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]");
        writer.WriteLine(Utils.GeneratedCodeAttributeList);
        writer.WriteLine($"private {@ref}struct __ut_Unmanaged");
        using (writer.EnterBracketIndentScope('{'))
        {
            foreach (var variant in data.Variants.Where(v => v.TypeData.TypeKind is VariantTypeKind.Unmanaged))
            {
                writer.WriteLine($"[global::System.Runtime.InteropServices.FieldOffset(0)]");
                writer.WriteLine($"public {variant.TypeData.FullyQName} _{variant.FieldId};");
            }
            if (data.Variants.Any(x => x.TypeData.TypeKind.IsPointer))
            {
                writer.WriteLine($"[global::System.Runtime.InteropServices.FieldOffset(0)]");
                writer.WriteLine($"public global::System.IntPtr _ptr;");
            }
        }
    }

    // emit: Dangerous

    private void EmitDangerousGetValueMethods(IndentedTextWriter writer, TypeUnionData data, Env env)
    {
        var c_allows = env.AllowsRefStruct ? ", allows ref struct" : "";

        // Reference
        if (data.Variants.Any(x => x.TypeData.TypeKind is VariantTypeKind.Reference))
        {
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteLine(Utils.AggressiveInliningAttributeList);
            if (env.UnscopedRef)
                writer.WriteLine(Utils.UnscopedRefAttributeList);
            writer.WriteLine($"private readonly ref readonly T DangerousGetReferenceTypeValueRef<T>() where T : class");
            using (writer.EnterBracketIndentScope('{'))
            {
                writer.WriteLine($"return ref global::System.Runtime.CompilerServices.Unsafe.As<object, T>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<object>(in this.__um_obj));");
            }

            writer.WriteLine();
        }

        // unmanaged
        if (data.Variants.Any(x => x.TypeData.TypeKind.IsUnmanaged && (env.AllowsRefStruct || !x.TypeData.IsRefLikeType)))
        {
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteLine(Utils.AggressiveInliningAttributeList);
            if (env.UnscopedRef)
                writer.WriteLine(Utils.UnscopedRefAttributeList);
            writer.WriteLine($"private readonly ref readonly T DangerousGetUnmanagedValueTypeValueRef<T>() where T : unmanaged{c_allows}");
            using (writer.EnterBracketIndentScope('{'))
            {
                writer.WriteLine($"return ref global::System.Runtime.CompilerServices.Unsafe.As<__ut_Unmanaged, T>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<__ut_Unmanaged>(in this.__um_unmanaged));");
            }

            writer.WriteLine();
        }

        // managed
        if (data.Variants.Any(x => x.TypeData.TypeKind is VariantTypeKind.Managed && (env.AllowsRefStruct || !x.TypeData.IsRefLikeType)))
        {
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteLine(Utils.AggressiveInliningAttributeList);
            if (env.UnscopedRef)
                writer.WriteLine(Utils.UnscopedRefAttributeList);
            writer.WriteLine($"private readonly ref readonly T DangerousGetManagedValueTypeValueRef<T>() where T : struct{c_allows}");
            using (writer.EnterBracketIndentScope('{'))
            {
                foreach (var item in data.Variants.Where(x => x.TypeData.TypeKind is VariantTypeKind.Managed))
                {
                    if (env.AllowsRefStruct || !item.TypeData.IsRefLikeType)
                    {
                        writer.WriteMultipleLines($$"""
                            if (typeof(T) == typeof({{item.TypeData.FullyQName}}))
                                return ref {{ExprVariantRefToT(item)}};
                            """);
                    }
                }
                writer.WriteLine("return ref global::System.Runtime.CompilerServices.Unsafe.NullRef<T>();");
            }

            writer.WriteLine();
        }

        // ref struct

        if (!env.AllowsRefStruct && data.Variants.Any(x => x.TypeData.IsRefLikeType))
        {
            foreach (var variant in data.Variants.Where(x => x.TypeData.IsRefLikeType))
            {
                writer.WriteLine(Utils.GeneratedCodeAttributeList);
                writer.WriteLine(Utils.AggressiveInliningAttributeList);
                if (env.UnscopedRef)
                    writer.WriteLine(Utils.UnscopedRefAttributeList);
                writer.WriteMultipleLines($$"""
                    private readonly ref readonly {{variant.TypeData.FullyQName}} DangerousGetValueRef_{{variant.ReadableIdentifier}}()
                    {
                        return ref {{ExprVariantRefToT(variant, variant.TypeData.FullyQName)}};
                    }
                    """);
                writer.WriteLine();
            }
        }

        // pointer

        if (data.Variants.Any(x => x.TypeData.TypeKind.IsPointer))
        {
            // void*
            writer.WriteLine(Utils.GeneratedCodeAttributeList);
            writer.WriteLine(Utils.AggressiveInliningAttributeList);
            if (env.UnscopedRef)
                writer.WriteLine(Utils.UnscopedRefAttributeList);
            writer.WriteLine($"private readonly unsafe ref readonly void* DangerousGetPointerTypeValueRef()");
            using (writer.EnterBracketIndentScope('{'))
            {
                writer.WriteLine($"return ref *(void**)global::System.Runtime.CompilerServices.Unsafe.AsPointer(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<__ut_Unmanaged>(in this.__um_unmanaged));");
            }
        }
    }

    // expr

    private string ExprVariantFieldAccess(VariantData variant, string @this = "this")
    {
        return variant.TypeData.TypeKind switch
        {
            VariantTypeKind.Pointer => $"{@this}.__um_unmanaged._ptr",
            VariantTypeKind.FunctionPointer => $"{@this}.__um_unmanaged._ptr",
            VariantTypeKind.Unmanaged => $"{@this}.__um_unmanaged._{variant.FieldId}",
            VariantTypeKind.Reference => $"{@this}.__um_obj",
            VariantTypeKind.Managed => $"{@this}.__um_managed{variant.FieldId}",
            _ => throw new NotImplementedException(),
        };
    }

    private string ExprVariantRefToT(VariantData variant, string targetType = "T")
    {
        var fieldFullyQualifiedTypeName = variant.TypeData.TypeKind switch
        {
            VariantTypeKind.Reference => "object",
            { IsPointer: true } => "global::System.IntPtr",
            _ => variant.TypeData.FullyQName,
        };
        if (fieldFullyQualifiedTypeName == targetType)
            return ExprVariantFieldAccess(variant);
        return $"global::System.Runtime.CompilerServices.Unsafe.As<{fieldFullyQualifiedTypeName}, {targetType}>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<{fieldFullyQualifiedTypeName}>(in {ExprVariantFieldAccess(variant)}))";
    }

    private string ExprVariantToT(VariantData variant, string? targetType = null)
    {
        if (!variant.TypeData.TypeKind.IsPointer)
            return ExprVariantRefToT(variant, targetType ?? "T");

        if (targetType is null)
        {
            var chars = (stackalloc char[variant.TypeData.PointerLevel + 1]);
            chars.Fill('*');
            chars[0] = 'T';
            targetType = chars.ToString();
        }

        return $"({targetType}){ExprVariantFieldAccess(variant)}";
    }

    // doc

    private static string DocCommentIsExactly(string type, bool code = true)
    {
        return $$"""
            /// <summary>
            /// Check if the union value is type {{(code ? $"<c>{type}</c>" : type)}}
            /// </summary>
            """;
    }

    static string DocCommentAsExactly(string type, bool code = true)
    {
        return $$"""
            /// <summary>
            /// Check if the union value is exactly type {{(code ? $"<c>{type}</c>" : type)}}, and return the value if it is.
            /// </summary>
            """;
    }

}