using System.CodeDom.Compiler;
using Trarizon.Library.Roslyn.SourceInfos.CSharp;

namespace Trarizon.Library.Functional.SourceGeneration;

internal static class Codes
{
    public static readonly string GeneratedCodeAttributeList = CodeFactory.GeneratedCodeAttributeList(
        typeof(Codes).Assembly.GetName().Name,
        typeof(Codes).Assembly.GetName().Version.ToString());

    public const string AutoGeneratedTrivia = "// <auto-generated />";
    public const string NullableEnableTrivia = "#nullable enable";

    public static void EmitTopTrivias(this IndentedTextWriter writer, bool autoGenerated, bool nullableEnable)
    {
        if (autoGenerated) {
            writer.WriteLine(AutoGeneratedTrivia);
            writer.WriteLine();
        }
        if (nullableEnable) {
            writer.WriteLine(NullableEnableTrivia);
            writer.WriteLine();
        }
    }
}
