using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using Trarizon.Library.Collections;

namespace Trarizon.Library.Roslyn.SourceInfos;
public static partial class CodeFactory
{
    public const string AutoGeneratedTopCommentTrivia = "// <auto-generated />";

    public static TypeHierarchyInfo GetTypeHierarchy(ITypeSymbol symbol, TypeDeclarationSyntax syntax)
    {
        var ns = symbol.ContainingNamespace;
        var nsInfo = ns.IsGlobalNamespace ? null : TypeHierarchyInfo.FromNamespace(ns.ToString());

        var types = syntax
            .AncestorsAndSelf()
            .OfTypeWhile<TypeDeclarationSyntax>()
            .Select(type => TypeDeclarationCodeInfoSelector(type, nsInfo));

        TypeHierarchyInfo first = types.First();

        TypeHierarchyInfo l = first;
        foreach (var r in types.Skip(1)) {
            l.Parent = r;
            l = r;
        }
        l.Parent = nsInfo;

        return first;
    }

    private static TypeHierarchyInfo TypeDeclarationCodeInfoSelector(TypeDeclarationSyntax syntax, TypeHierarchyInfo? @namespace)
    {
        var keyword = syntax is RecordDeclarationSyntax rcd
            ? $"{rcd.Keyword} {rcd.ClassOrStructKeyword}"
            : syntax.Keyword.ToString();
        return new TypeHierarchyInfo(@namespace?.Name, keyword, $"{syntax.Identifier}{syntax.TypeParameterList}");
    }
}